#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_BienTap.cshtml")]
    public partial class _Views_MapIOT__BienTap_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__BienTap_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal fade bs-example-modal-lg modal-bien-tap\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myLargeModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close close-modal-iotlink\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Close</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral("> Biên tập bản đồ</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <iframe");

WriteLiteral(" id=\"svgEditor\"");

WriteLiteral(" class=\"svg-editor\"");

WriteLiteral(" src=\"\"");

WriteLiteral(@" ></iframe>
            </div>
        </div>
    </div>
</div>
    <style>
        .modal-bien-tap {
            width: 100%;
            padding: 0px !important;
        }

            .modal-bien-tap .modal-dialog {
                width: 100%;
                padding: 5px;
                margin: 0px;
            }

            .modal-bien-tap .modal-header {
                position: relative;
            }

            .modal-bien-tap .modal-body {
                height: calc(100vh - 70px);
                display: flex;
                padding: 0px !important;
            }
            .modal-body iframe{
                width:100%;
            }

    </style>
<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1393), Tuple.Create("\"", 1426)
, Tuple.Create(Tuple.Create("", 1399), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/BienTap.js")
, 1399), false)
);

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
