#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_ChuGiai.cshtml")]
    public partial class _Views_MapIOT__ChuGiai_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__ChuGiai_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"dieuKhienChuGiai\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-file-text-o\"");

WriteLiteral("></i> Chú giải</button>\r\n<button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn_loaisudung\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-filter\"");

WriteLiteral("></i> Bộ lọc</button>\r\n<div");

WriteLiteral(" class=\"chuGiai\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"phanTop\"");

WriteLiteral(">\r\n        <h5");

WriteLiteral(" class=\"tieuDe\"");

WriteLiteral(">Phân loại chức năng sử dụng đất</h5>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close close-modal-iotlink tatChuGiai\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n        </button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"noiDung\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"listChuGiai\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"contentChuGiai\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #6EFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng tự nhiên đặc dụng</div>\r\n                </div>\r\n\r\n                <" +
"div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #CDAACD; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất bãi thải, xử lý chất thải</div>\r\n                </div>\r\n\r\n                <" +
"div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ff870f; border:1px solid #ff962d\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất ở hiện hữu</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFF0B4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất bằng trồng cây hàng năm khác</div>\r\n                </div>\r\n\r\n              " +
"  <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở dịch vụ xã hội</div>\r\n                </div>\r\n\r\n             " +
"   <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có mặt nước chuyên dùng</div>\r\n                </div>\r\n\r\n                <di" +
"v");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng lúa nước còn lại</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #faaaa0; border:1px solid #6e6e6e\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất cơ sở sản xuất phi nông nghiệp</div>\r\n                </div>\r\n\r\n            " +
"    <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất mặt nước ven biển có mục đích khác</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #BEFF1E; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất khoanh nuôi phục hồi rừng phòng hộ</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFCB4; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng lúa nương</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #6EFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng rừng đặc dụng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất công trình bưu chính, viễn  thông</div>\r\n                </div>\r\n\r\n         " +
"       <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nuôi trồng thuỷ sản</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có mặt nước ven biển</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFD2A0; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây lâu năm</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFD7AA; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây ăn quả lâu năm</div>\r\n                </div>\r\n\r\n                <d" +
"iv");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFFFE; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất đồi núi chưa sử dụng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở khoa học và công nghệ</div>\r\n                </div>\r\n\r\n      " +
"          <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất mặt nước ven biển có rừng ngập mặn</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #7f7f00; border:1px solid #7f7f00\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất Quân đội</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất phi nông nghiệp khác</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFC78; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây hàng năm</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ff0000; border:1px solid #ff0000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất công trình dich vụ công cộng</div>\r\n                </div>\r\n\r\n              " +
"  <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng rừng sản xuất</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFFFF; border:1px solid #AAFFFF\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất thuỷ lợi</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #5200a5; border:1px solid #5200a5\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất khu công nghiệp</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất chuyên trồng lúa nước</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #6EFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng trồng đặc dụng</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFFFE; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất chưa sử dụng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ff0000; border:1px solid #ff0000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất quy hoạch cở sở giáo dục - đào tạo</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trụ sở khác</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFF32; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất lâm nghiệp</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #6EFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất khoanh nuôi phục hồi rừng đặc dụng</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ffdf7f; border:1px solid #ffdf7f\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nhóm nhà ở xây dựng mới</div>\r\n                </div>\r\n\r\n                <di" +
"v");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFF0B4; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây hàng năm khác</div>\r\n                </div>\r\n\r\n                <di" +
"v");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FF5046; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất an ninh</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #E6E6C8; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Núi đá không có rừng cây</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #CDAACD; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất sản xuất vật liệu xây dựng, làm đồ gốm</div>\r\n                </div>\r\n\r\n    " +
"            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #7f3f00; border:1px solid #7f3f00\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng trụ sở cơ quan</div>\r\n                </div>\r\n\r\n                <di" +
"v");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #BEFF1E; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng rừng phòng hộ</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất khoanh nuôi phục hồi rừng sản xuất</div>\r\n                </div>\r\n\r\n        " +
"        <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nuôi trồng thuỷ sản nước lợ, mặn</div>\r\n                </div>\r\n\r\n          " +
"      <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất công trình năng lượng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #bf7fff; border:1px solid #bf7fff\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất bãi xe</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #a52900; border:1px solid #6e6e6e\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở y tế</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất rừng sản xuất</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFA0AA; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất sản xuất, kinh doanh phi nông nghiệp</div>\r\n                </div>\r\n\r\n      " +
"          <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng trồng sản xuất</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #E6E682; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất cỏ dùng vào chăn nuôi</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng tự nhiên sản xuất</div>\r\n                </div>\r\n\r\n                <" +
"div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở văn hóa</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ff6450; border:1px solid #6e6e6e\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất quốc phòng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFF0B4; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nương rẫy trồng cây hàng năm khác</div>\r\n                </div>\r\n\r\n         " +
"       <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ffff00; border:1px solid #ffff00\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất ở</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFC6E; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">SXN</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFFFE; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất làm muối</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFD0FF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất ở tại nông thôn</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #BEFF1E; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng trồng phòng hộ</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất cơ sở  tôn giáo</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ff7f9f; border:1px solid #ff7f9f\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất hỗn hợp (CT TMDV CC + ở)</div>\r\n                </div>\r\n\r\n                <d" +
"iv");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất tôn giáo, tín ngưỡng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFFFE; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất bằng chưa sử dụng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #D2D2D2; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nghĩa trang, nghĩa địa, nhà tang lễ, nhà hỏa táng</div>\r\n                </d" +
"iv>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFC82; border:1px solid #000\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng lúa</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFD7AA; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây công nghiệp lâu năm</div>\r\n                </div>\r\n\r\n             " +
"   <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #B4FFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất mặt nước ven biển nuôi trồng thuỷ sản</div>\r\n                </div>\r\n\r\n     " +
"           <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAA32; border:1px solid #FFAA32\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất giao thông</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFA0AA; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trụ sở cơ quan, công trình sự nghiệp</div>\r\n                </div>\r\n\r\n      " +
"          <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất chợ</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #CDAACD; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất sử dụng cho hoạt động khoáng sản</div>\r\n                </div>\r\n\r\n          " +
"      <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #0000ff; border:1px solid #0000ff\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở giáo dục - đào tạo</div>\r\n                </div>\r\n\r\n         " +
"       <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #BEFF1E; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất rừng phòng hộ</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #00a500; border:1px solid #00a500\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất cây xanh</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFD7AA; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất trồng cây lâu năm khác</div>\r\n                </div>\r\n\r\n                <div" +
"");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có di tích</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #ffa0ff; border:1px solid #6e6e6e\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất ở tại đô thị</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất phi nông nghiệp</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất cơ sở  tín ngưỡng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất xây dựng cơ sở thể dục - thể thao</div>\r\n                </div>\r\n\r\n         " +
"       <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #6EFF64; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất rừng đặc dụng</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #A0FFFF; border:1px solid #A0FFFF\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất sông, ngòi, kênh, rạch, suối</div>\r\n                </div>\r\n\r\n              " +
"  <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFFFB4; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nông nghiệp khác</div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #BEFF1E; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất có rừng tự nhiên phòng hộ</div>\r\n                </div>\r\n\r\n                <" +
"div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #FFAAA0; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất sử dụng vào mục đích công cộng</div>\r\n                </div>\r\n\r\n            " +
"    <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"viewColor\"");

WriteLiteral(" style=\"background-color: #AAFFFF; border:1px solid #6E6E6E\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"name\"");

WriteLiteral(">Đất nuôi trồng thuỷ sản nước ngọt</div>\r\n                </div>\r\n            <di" +
"v");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                    \r\n                </div>\r\n            </div>\r\n        </di" +
"v>\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" class=\"loaisudung\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"phanTop\"");

WriteLiteral(">\r\n        <h5");

WriteLiteral(" class=\"tieuDe\"");

WriteLiteral(">Bộ lọc</h5>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close tatChuGiai\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n        </button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"noiDung\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"view-layer-all\"");

WriteLiteral(">\r\n            <h5");

WriteLiteral(" class=\"tieuDeChuThich\"");

WriteLiteral(">Phân loại lớp đất</h5>\r\n            <div");

WriteLiteral(" class=\"listLopDat list\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"chuThich\"");

WriteLiteral(">\r\n            <h5");

WriteLiteral(" class=\"tieuDeChuThich\"");

WriteLiteral(">Phân loại chức năng sử dụng đất</h5>\r\n            <div");

WriteLiteral(" class=\"listLoaiSuDung list\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"footer-loaisudung\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"btn btn-default btn-filter-loaisudung\"");

WriteLiteral(">Lọc loại sử dụng đất</button>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
