#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_EditMode3D.cshtml")]
    public partial class _Views_MapIOT__EditMode3D_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__EditMode3D_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal fade bs-example-modal-lg modal-edit-mode-3d\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myLargeModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"loading-map-mode3d\"");

WriteLiteral(" class=\"loading-map\"");

WriteLiteral(" style=\"display: none;background-color: #0000;\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 307), Tuple.Create("\"", 340)
, Tuple.Create(Tuple.Create("", 313), Tuple.Create<System.Object, System.Int32>(Href("~/Images/MapIOT/loading.gif")
, 313), false)
);

WriteLiteral(" />\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close close-modal-iotlink\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Close</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral("> Biên tập không gian 3D</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"option-mode-3d\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"box-body project-content\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"parent-info-mode-3d\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row info-mode-3d\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group col-lg-12 col-md-12\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label required\"");

WriteLiteral(" for=\"Name\"");

WriteLiteral(">Tên<span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>:\r\n                                    <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"Tên là bắt buộc\"");

WriteLiteral(" id=\"txtName\"");

WriteLiteral(" name=\"Name\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                          <div");

WriteLiteral(" class=\"row changeModel\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"required title-common col-lg-12 col-md-12\"");

WriteLiteral(">Không gian 3D <span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span></label>\r\n                                <div");

WriteLiteral(" class=\"control-group form-group col-lg-12 col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row option-draw-3d\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                                            <label>\r\n                         " +
"                       <input");

WriteLiteral(" name=\"modelObject\"");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" class=\"ace\"");

WriteLiteral(" value=\"2\"");

WriteLiteral(" id=\"drawObject\"");

WriteLiteral(" checked>\r\n                                                <span");

WriteLiteral(" class=\"lbl\"");

WriteLiteral("> Vẽ đáy</span>\r\n                                            </label>\r\n          " +
"                              </div>\r\n                                        <d" +
"iv");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                                            <label>\r\n                         " +
"                       <input");

WriteLiteral(" name=\"modelObject\"");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" class=\"ace\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" id=\"modelObject\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"lbl\"");

WriteLiteral("> Tải lên</span>\r\n                                            </label>\r\n         " +
"                               </div>\r\n                                        <" +
"div");

WriteLiteral(" class=\"radio\"");

WriteLiteral(">\r\n                                            <label>\r\n                         " +
"                       <input");

WriteLiteral(" name=\"modelObject\"");

WriteLiteral(" type=\"radio\"");

WriteLiteral(" class=\"ace\"");

WriteLiteral(" value=\"3\"");

WriteLiteral(" id=\"defaultObject\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"lbl\"");

WriteLiteral("> Mẫu có sẳn</span>\r\n                                            </label>\r\n      " +
"                                  </div>\r\n                                    </" +
"div>\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"upload-object\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                                <label");

WriteLiteral(" class=\"upload-model\"");

WriteLiteral(">\r\n                                                    <input");

WriteLiteral(" accept=\"image/x-png,image/jpeg,.obj\"");

WriteLiteral(" multiple=\"\"");

WriteLiteral(" class=\"obj-file\"");

WriteLiteral(" id=\"objFile\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-upload\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>Tải lên\r\n                                                </label>\r\n         " +
"                                   </div>\r\n                                     " +
"   </div>\r\n                                        <div");

WriteLiteral(" class=\"draw-object col-lg-12 col-md-12\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"form-group hinhdangday\"");

WriteLiteral(">\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm\"");

WriteLiteral(" id=\"btnStartDraw\"");

WriteLiteral(">Bắt đầu vẽ</button>\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary btn-sm hide\"");

WriteLiteral(" id=\"btnEditDraw\"");

WriteLiteral(">Chỉnh sửa</button>\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-sm hide\"");

WriteLiteral(" id=\"btnEndDraw\"");

WriteLiteral(">Kết thúc vẽ</button>\r\n                                                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-danger btn-sm hide\"");

WriteLiteral(" id=\"btnDeleteDraw\"");

WriteLiteral(">Xóa</button>\r\n                                                <div");

WriteLiteral(" class=\"form-group errorDrawEmpty\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                                    <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">Vui lòng đáy phải trong thửa đất!</span>\r\n                                      " +
"          </div>\r\n                                            </div>\r\n          " +
"                              </div>\r\n                                        <d" +
"iv");

WriteLiteral(" class=\"object-mode\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                                            <select");

WriteLiteral(" class=\"object-mode-3d form-control\"");

WriteLiteral("></select>\r\n                                        </div>\r\n                     " +
"               </div>\r\n                                </div>\r\n                 " +
"           </div>\r\n                            <div");

WriteLiteral(" class=\"row properti-mode-3d\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Tỉ lệ<span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span>:</label>\r\n                                    <input");

WriteLiteral(" value=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"Scale\"");

WriteLiteral(" name=\"Scale\"");

WriteLiteral(" />\r\n                                </div>\r\n                                <div" +
"");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Góc xoay<span");

WriteLiteral(" style=\"color: red\"");

WriteLiteral(">*</span>:</label>\r\n                                    <input");

WriteLiteral(" value=\"0\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"Bearing\"");

WriteLiteral(" name=\"Bearing\"");

WriteLiteral(" />\r\n\r\n                                </div>\r\n                                <d" +
"iv");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Chiều cao</label><i> (m)</i>:\r\n                                    <input");

WriteLiteral(" value=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"HeightScale\"");

WriteLiteral(" name=\"HeightScale\"");

WriteLiteral(" />\r\n                                </div>\r\n                                <div" +
"");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Cao độ</label> <i> (mực nước biển)</i>:\r\n                                    <in" +
"put");

WriteLiteral(" value=\"0\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"Elevation\"");

WriteLiteral(" name=\"Elevation\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                            <div");

WriteLiteral(" class=\"row info-mode-3d\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">Số tầng</label>:\r\n                                    <input");

WriteLiteral(" value=\"1\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"Heightfloor\"");

WriteLiteral(" name=\"Heightfloor\"");

WriteLiteral(" />\r\n                                </div>\r\n                                <div" +
"");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(" for=\"AreaFloor\"");

WriteLiteral(">Diện tích sàn</label><i> (m<sup>2</sup>)</i>:\r\n                                 " +
"   <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-number=\"The field Cao độ must be a number.\"");

WriteLiteral(" id=\"AreaFloor\"");

WriteLiteral(" name=\"AreaFloor\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" typenumber=\"float\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-group\"");

WriteLiteral(">\r\n                                    <label");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(" for=\"TotalAreaFloor\"");

WriteLiteral(">Tổng diện tích sàn</label><i> (m<sup>2</sup>)</i>:\r\n                            " +
"        <input");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-number=\"The field Cao độ must be a number.\"");

WriteLiteral(" id=\"TotalAreaFloor\"");

WriteLiteral(" name=\"TotalAreaFloor\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" typenumber=\"float\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                        <div");

WriteLiteral(" class=\"btn-footer\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-save-mode-3d\"");

WriteLiteral(">Lưu lại</button>\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-light\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Hủy bỏ</button>\r\n                        </div>\r\n                    </div>\r\n   " +
"             </div>\r\n                <div");

WriteLiteral(" class=\"map-mode-3d\"");

WriteLiteral(" id=\"mapMode3D\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n<style>\r\n    .mo" +
"dal-edit-mode-3d .modal-dialog {\r\n        width: 100%;\r\n        margin: 0px;\r\n  " +
"      height: 100%;\r\n    }\r\n\r\n    .modal-edit-mode-3d .modal-body {\r\n        pad" +
"ding: 0px;\r\n        display: flex;\r\n        height: calc(100% - 60px);\r\n    }\r\n\r" +
"\n    .modal-edit-mode-3d .modal-content {\r\n        height: 100%;\r\n    }\r\n\r\n    ." +
"modal-edit-mode-3d .option-mode-3d {\r\n        width: 300px;\r\n        height: 100" +
"%;\r\n        background: #f5fbff;\r\n        position: relative;\r\n    }\r\n\r\n    .mod" +
"al-edit-mode-3d button.close {\r\n        top: 14px;\r\n        opacity: 1;\r\n    }\r\n" +
"\r\n    .modal-edit-mode-3d .map-mode-3d {\r\n        width: calc(100% - 300px);\r\n  " +
"  }\r\n\r\n    .modal-edit-mode-3d .radio + .radio, .modal-edit-mode-3d .checkbox + " +
".checkbox {\r\n        margin: none;\r\n    }\r\n\r\n    .modal-edit-mode-3d .option-dra" +
"w-3d {\r\n        display: flex;\r\n        align-items: baseline;\r\n    }\r\n\r\n    .mo" +
"dal-edit-mode-3d .upload-model {\r\n        cursor: pointer;\r\n        width: 378px" +
";\r\n        height: 36px;\r\n        background-color: #2da1f8;\r\n        /*border-r" +
"adius: 4px;*/\r\n        border: none;\r\n        line-height: normal;\r\n        font" +
"-size: 14px;\r\n        color: #fff;\r\n        display: -ms-flexbox;\r\n        displ" +
"ay: flex;\r\n        -ms-flex-pack: center;\r\n        justify-content: center;\r\n   " +
"     -ms-flex-align: center;\r\n        align-items: center;\r\n        /*padding-le" +
"ft: 32px;\r\n        text-align: center;*/\r\n    }\r\n\r\n    .modal-edit-mode-3d .hinh" +
"dangday button {\r\n        border-radius: 0px;\r\n    }\r\n\r\n    .modal-edit-mode-3d " +
".hinhdangday .btn-primary {\r\n        background-color: #2da1f8;\r\n        border-" +
"color: #2da1f8;\r\n    }\r\n\r\n    .modal-edit-mode-3d .project-content {\r\n        pa" +
"dding: 0px;\r\n        padding-top: 15px;\r\n        height: 100%;\r\n    }\r\n\r\n    .mo" +
"dal-edit-mode-3d .row {\r\n        margin-left: 0px;\r\n        margin-right: 0px;\r\n" +
"    }\r\n\r\n    .modal-edit-mode-3d .btn-footer {\r\n        position: absolute;\r\n   " +
"     bottom: 0px;\r\n        width: 100%;\r\n        display: flex;\r\n    }\r\n\r\n      " +
"  .modal-edit-mode-3d .btn-footer button {\r\n            width: 50%;\r\n           " +
" border-radius: 0px;\r\n        }\r\n\r\n    .form-group .ui-widget-content {\r\n       " +
" width: 100%;\r\n        height: 35px;\r\n    }\r\n    /*.object-mode .select2-contain" +
"er{\r\n        width:100% !important;\r\n    }\r\n    .object-mode .select2-container " +
".select2-selection--single{\r\n        height:34px;\r\n    }*/\r\n    ");

WriteLiteral(@"@media (max-height: 810px) {
        .modal-edit-mode-3d .project-content{
            overflow-y: auto !important;
             padding-top:0px;
        }
        .modal-edit-mode-3d .parent-info-mode-3d {
            padding-bottom: 20px;
            overflow-y: auto !important;
        }
        .modal-edit-mode-3d .btn-footer{
            position: unset !important;
        }
    }
    ");

WriteLiteral(@"@media (max-width: 810px) {
        .modal-edit-mode-3d .project-content{
            overflow-y: auto !important;
            padding-top:0px;
        }
        .modal-edit-mode-3d .parent-info-mode-3d {
            padding-bottom: 20px;
            overflow-y: auto !important;
        }
        .modal-edit-mode-3d .btn-footer{
            position: unset !important;
        }
    }

</style>");

        }
    }
}
#pragma warning restore 1591
