#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_MenuLeft.cshtml")]
    public partial class _Views_MapIOT__MenuLeft_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__MenuLeft_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<a");

WriteLiteral(" id=\"show-sidebar\"");

WriteLiteral(" class=\"btn btn-sm btn-dark\"");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(">\r\n    <i");

WriteLiteral(" class=\"fa fa-bars\"");

WriteLiteral("></i>\r\n</a>\r\n<div");

WriteLiteral(" class=\"menu-district open-menu\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"phanTop\"");

WriteLiteral(">\r\n        <h5");

WriteLiteral(" class=\"tieuDe\"");

WriteLiteral(">Menu địa chính</h5>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close tatMenuLeft\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</span>\r\n        </button>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"ShowAll\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" style=\"padding: 0px 4px;margin-bottom: 0px;\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"has-children has-all-map\"");

WriteLiteral(" id=\"0\"");

WriteLiteral(" data-id=\"0\"");

WriteLiteral(" data-code=\"0\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" class=\"input-checkbox\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" id=\"label-menu-left\"");

WriteLiteral(">Tất cả<i");

WriteLiteral(" class=\"fa fa-chevron-left\"");

WriteLiteral(" style=\"padding-left:12px; float:right;display:none;\"");

WriteLiteral("></i></label>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"noiDung2\"");

WriteLiteral(" id=\"scrollbar\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"cd-accordion-menu animated\"");

WriteLiteral(" id=\"menu-list\"");

WriteLiteral(">\r\n        </ul>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
