#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_MenuPartial.cshtml")]
    public partial class _Views_MapIOT__MenuPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__MenuPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<aside");

WriteLiteral(" class=\"main-sidebar\"");

WriteLiteral(">\r\n    <!-- sidebar: style can be found in sidebar.less -->\r\n    <section");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(" style=\"height: auto;\"");

WriteLiteral(">\r\n        <!-- /.search form -->\r\n        <!-- sidebar menu: : style can be foun" +
"d in sidebar.less -->\r\n        <div");

WriteLiteral(" class=\"header\"");

WriteLiteral(" id=\"li-header\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-map\"");

WriteLiteral(" title=\"Tải bản đồ thửa đất\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> <span>Tải bản đồ thửa đất</span>\r\n        </div>\r\n        <ul");

WriteLiteral(" class=\"sidebar-menu tree\"");

WriteLiteral(" id=\"load-menu-left-thua-dat\"");

WriteLiteral(" data-widget=\"tree\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"treeview has-children has-all-map\"");

WriteLiteral(" id=\"0\"");

WriteLiteral(" data-id=\"0\"");

WriteLiteral(" data-code=\"0\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                    <i");

WriteLiteral(" class=\"fa fa-circle-o text-blue\"");

WriteLiteral("></i> <span>Tất cả</span>\r\n                </a>\r\n            </li>\r\n        </ul>" +
"\r\n        ");

WriteLiteral("\r\n    </section>\r\n</aside>");

        }
    }
}
#pragma warning restore 1591
