#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_NhapDuLieuFile.cshtml")]
    public partial class _Views_MapIOT__NhapDuLieuFile_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__NhapDuLieuFile_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal\"");

WriteLiteral(" id=\"textfileModal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\r\n            <!-- Modal Header -->\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding-bottom:0;\"");

WriteLiteral(">\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Nhập dữ liệu từ textfile</h4>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"close-modal\"");

WriteLiteral(" class=\"close close-modal-importfile\"");

WriteLiteral(">&times;</button>\r\n            </div>\r\n\r\n            <!-- Modal body -->\r\n       " +
"     <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-3 col-xs-12 required\"");

WriteLiteral(">TextFile</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-9 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <label");

WriteLiteral(" class=\"custom-file-upload\"");

WriteLiteral(" id=\"custom-file-upload-1\"");

WriteLiteral(">\r\n                                    <input");

WriteLiteral(" hidden=\"hidden\"");

WriteLiteral(" id=\"Files-1\"");

WriteLiteral(" name=\"Files\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" data-id=\"1\"");

WriteLiteral(" accept=\".geojson, .json, .txt\"");

WriteLiteral(">\r\n                                    Chọn tệp...\r\n                             " +
"   </label>\r\n                                <div>Các định dạng được phép chọn: " +
"<strong> .txt, .json, .geojson</strong></div>\r\n                                <" +
"div");

WriteLiteral(" class=\"fileUpLoadError text-danger\"");

WriteLiteral(" id=\"fileUpLoadError\"");

WriteLiteral("></div>\r\n                                <div");

WriteLiteral(" class=\"fileNames\"");

WriteLiteral(" style=\"margin-top: 10px;font-weight: 600;font-style: italic;\"");

WriteLiteral("></div>.\r\n                            </div>\r\n                        </div>\r\n   " +
"                 </div>\r\n                </div>\r\n\r\n            </div>\r\n\r\n       " +
"     <!-- Modal footer -->\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default close-modal-importfile\"");

WriteLiteral(">Thoát</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btn-upload-file\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Lưu lại</button>\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
