#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_TachThua.cshtml")]
    public partial class _Views_MapIOT__TachThua_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__TachThua_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"modal fade bs-example-modal-lg modal-tach-thua\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myLargeModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close close-modal-iotlink\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">&times;</span><span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Close</span></button>\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral("> Tách thửa đất</h4>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"menu-tach-thua\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"height: 100%;overflow-y:auto\"");

WriteLiteral(">\r\n                        <div>\r\n                            <ul>\r\n             " +
"                   <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-cach-duong-thang active\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-list-alt\"");

WriteLiteral("></i> Giao hội cách đường thẳng</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-hoi-thuan\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-tachometer\"");

WriteLiteral("></i> Giao hội thuận</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-hoi-nghich\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-desktop\"");

WriteLiteral("></i> Giao hội nghịch</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-hoi-huong\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-list\"");

WriteLiteral("></i> Giao hội hướng</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-doc-theo-canh\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-pencil-square-o\"");

WriteLiteral("></i> Giao hội dọc theo cạnh</a></li>\r\n                                <li><a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"menu-nhap-toa-do\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-list-alt\"");

WriteLiteral("></i> Nhập tọa độ</a></li>\r\n                            </ul>\r\n                  " +
"      </div>\r\n\r\n                        <table");

WriteLiteral(" class=\"table table-hover table-point\"");

WriteLiteral(">\r\n                            <thead>\r\n                                <tr>\r\n   " +
"                                 <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Id</th>\r\n                                    <th");

WriteLiteral(" scope=\"col\"");

WriteLiteral(">Phương thức</th>\r\n                                </tr>\r\n                       " +
"     </thead>\r\n                            <tbody");

WriteLiteral(" id=\"pointGhiNhan\"");

WriteLiteral("></tbody>\r\n                        </table>\r\n                        <div");

WriteLiteral(" class=\"button-tool\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default clear-all-point\"");

WriteLiteral(" title=\"Xóa toàn bộ điểm chia\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-trash-o\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></button>\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default view-tach-thua\"");

WriteLiteral(" title=\"Xem kết quả tách thửa\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-play\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></button>\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default clear-result\"");

WriteLiteral(" title=\"Xóa kết quả tách thửa\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-refresh\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></button>\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default save-tach-thua\"");

WriteLiteral(" title=\"Lưu kết quả\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-pencil-square-o\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></button>\r\n                        </div>\r\n                    </div>\r\n\r\n   " +
"             </div>\r\n                <div");

WriteLiteral(" class=\"map-tach-thua\"");

WriteLiteral(" id=\"madTachThua\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"footer-map-point col-xs-12 col-sm-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"header-point\"");

WriteLiteral(">\r\n                            <h4");

WriteLiteral(" class=\"title-giao-hoi\"");

WriteLiteral(">Giao hội</h4>\r\n                            <span");

WriteLiteral(" class=\"btn-show-hide-point\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-chevron-down\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></span>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"context-point\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-xs-12 col-sm-8\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"col-xs-12 col-sm-12 form-giao-hoi\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-10\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"sel_GHDoc1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Đỉnh A</label>\r\n                                                        <select");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(" id=\"sel_GHCDTDinhA\"");

WriteLiteral("></select>\r\n                                                    </div>\r\n         " +
"                                           <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"sel_GHDoc2\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Đỉnh B</label>\r\n                                                        <select");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(" id=\"sel_GHCDTDinhB\"");

WriteLiteral("></select>\r\n                                                    </div>\r\n         " +
"                                       </div>\r\n                                 " +
"               <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"sel_GHDoc1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Đỉnh C</label>\r\n                                                        <select");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(" id=\"sel_GHCDTDinhC\"");

WriteLiteral("></select>\r\n                                                    </div>\r\n         " +
"                                           <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"sel_GHDoc2\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Đỉnh D</label>\r\n                                                        <select");

WriteLiteral(" class=\"col-sm-8\"");

WriteLiteral(" id=\"sel_GHCDTDinhD\"");

WriteLiteral("></select>\r\n                                                    </div>\r\n         " +
"                                       </div>\r\n                                 " +
"               <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-9\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Cách AB</label>\r\n                                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-8 input-mask-distance\"");

WriteLiteral(" placeholder=\"Khoảng cách (m)\"");

WriteLiteral(" id=\"inp_CachAB\"");

WriteLiteral(">\r\n                                                    </div>\r\n\r\n                " +
"                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-9\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Cách CD</label>\r\n                                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-8 input-mask-distance\"");

WriteLiteral(" placeholder=\"Khoảng cách (m)\"");

WriteLiteral(" id=\"inp_CachCD\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                              </div>\r\n                                          " +
"      <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-9\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Cạnh A-C</label>\r\n                                                        <input" +
"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-8 input-mask-distance\"");

WriteLiteral(" placeholder=\"Độ dài cạnh (m)\"");

WriteLiteral(" id=\"inp_CanhAC\"");

WriteLiteral(">\r\n                                                    </div>\r\n\r\n                " +
"                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-9\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Cạnh B-C</label>\r\n                                                        <input" +
"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"col-sm-8 input-mask-distance\"");

WriteLiteral(" placeholder=\"Độ dài cạnh (m)\"");

WriteLiteral(" id=\"inp_CanhBC\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                              </div>\r\n                                          " +
"      <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-select-1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Góc CAB</label>\r\n                                                        <input");

WriteLiteral(" class=\"col-sm-8 input-mask-angle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"inp_GocCAB\"");

WriteLiteral(" disabled=\"\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                                  <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-select-1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Góc CBA</label>\r\n                                                        <input");

WriteLiteral(" class=\"col-sm-8 input-mask-angle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"inp_GocCBA\"");

WriteLiteral(" disabled=\"\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                              </div>\r\n                                          " +
"      <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-select-1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Góc APB</label>\r\n                                                        <input");

WriteLiteral(" class=\"col-sm-8 input-mask-angle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"inp_GocAPB\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                                  <div");

WriteLiteral(" class=\"col-xs-12 col-sm-6\"");

WriteLiteral(">\r\n                                                        <label");

WriteLiteral(" for=\"form-field-select-1\"");

WriteLiteral(" class=\"col-sm-4 control-label no-padding-right\"");

WriteLiteral(">Góc APC</label>\r\n                                                        <input");

WriteLiteral(" class=\"col-sm-8 input-mask-angle\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"inp_GocAPC\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                              </div>\r\n                                          " +
"      <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-4\"");

WriteLiteral(">\r\n                                                        <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                                                        </div>\r\n              " +
"                                      </div>\r\n                                  " +
"              </div>\r\n                                                <div");

WriteLiteral(" class=\"form-group row\"");

WriteLiteral(">\r\n                                                    <div");

WriteLiteral(" class=\"col-xs-12 col-sm-4\"");

WriteLiteral(">\r\n                                                    </div>\r\n                  " +
"                              </div>\r\n                                          " +
"  </div>\r\n                                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-2\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"control-group\"");

WriteLiteral(">\r\n                                                </div>\r\n                      " +
"                      </div>\r\n                                            <div");

WriteLiteral(" class=\"col-xs-12 col-sm-2\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"phương-thuc-giao-hoi-thuan\"");

WriteLiteral(">\r\n                                                </div>\r\n                      " +
"                      </div>\r\n                                        </div>\r\n  " +
"                                  </div>\r\n                                    <d" +
"iv");

WriteLiteral(" class=\"form-actions center\"");

WriteLiteral(">\r\n                                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-warning\"");

WriteLiteral(" id=\"btn_Clear\"");

WriteLiteral(">\r\n                                            Làm lại\r\n                         " +
"                   <i");

WriteLiteral(" class=\"ace-icon fa fa-refresh icon-on-right bigger-110\"");

WriteLiteral("></i>\r\n                                        </button>\r\n                       " +
"                 <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-warning\"");

WriteLiteral(" id=\"btn_Preview\"");

WriteLiteral(">\r\n                                            Xem thử\r\n                         " +
"                   <i");

WriteLiteral(" class=\"ace-icon fa fa-arrow-right icon-on-right bigger-110\"");

WriteLiteral("></i>\r\n                                        </button>\r\n                       " +
"                 <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-sm btn-success\"");

WriteLiteral(" id=\"btn_Submit\"");

WriteLiteral(">\r\n                                            Ghi nhận\r\n                        " +
"                    <i");

WriteLiteral(" class=\"ace-icon fa fa-plus icon-on-right bigger-110\"");

WriteLiteral("></i>\r\n                                        </button>\r\n\r\n                     " +
"               </div>\r\n                                </div>\r\n                 " +
"               <div");

WriteLiteral(" class=\"col-xs-6 col-sm-2 col-md-4\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"thumbnail search-thumbnail note-giao-hoi\"");

WriteLiteral(">\r\n                                        <img");

WriteLiteral(" class=\"media-object\"");

WriteLiteral(" alt=\"100%x200\"");

WriteLiteral(" src=\"/Images/MapIOT/GiaoHoi/ghcachduongthang.png\"");

WriteLiteral(" data-holder-rendered=\"true\"");

WriteLiteral(" style=\"height: 100%; width: 100%; display: block;\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(@">
                                            <p>Lấy ra điểm cách đường AB, CD lần lượt các khoảng là d1 và d2. Kết quả sẽ thu được là 4 điểm 1,2,3,4.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div");

WriteLiteral(" class=\"infor-Tach-Thua\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"height: 90%;overflow-y:auto;overflow-x: hidden;\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" name=\"id\"");

WriteLiteral(" hidden />\r\n                        <div");

WriteLiteral(" class=\"header-infor\"");

WriteLiteral(">\r\n                            <span><i");

WriteLiteral(" class=\"fa fa-times-circle\"");

WriteLiteral(" title=\"Đóng\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i></span>\r\n                            <h4>Thông tin thửa đất</h4>\r\n          " +
"              </div>\r\n                        <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Số tờ bản đồ <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span></label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soTo\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số hiệu tờ bản đồ\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Số thứ tự thửa <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span></label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soThua\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số thứ tự thửa\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Tờ bản đồ cũ</label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soTo-old\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Tờ bản đồ cũ\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Thửa cũ</label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soThua-old\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Thửa cũ\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Diện tích <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span></label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-update-dienTich\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Diện tích\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" oninput=\"this.value = this.value.replace(/[^0-9.]/g, \'\').replace(/(\\..*)\\./g, \'$" +
"1\');\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Diện tích pháp lý <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span></label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-update-dienTichPhapLy\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Diện tích pháp lý\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" oninput=\"this.value = this.value.replace(/[^0-9.]/g, \'\').replace(/(\\..*)\\./g, \'$" +
"1\');\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Mục đích sử dụng <span");

WriteLiteral(" style=\"color:red\"");

WriteLiteral(">*</span></label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 210 "..\..\Views\MapIOT\_TachThua.cshtml"
                           Write(Html.DropDownList("KH", new List<SelectListItem>()
            
            #line default
            #line hidden
            
            #line 210 "..\..\Views\MapIOT\_TachThua.cshtml"
                                                                                                                    , new { @id = "KH-listselectid", @class = "KH-select", autocomplete = "off" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"             <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Tên chủ</label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-update-chuNha\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Tên chủ sở hữu\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                            <label");

WriteLiteral(" class=\"control-label col-md-5 col-xs-12 required\"");

WriteLiteral(">Địa chỉ</label>\r\n                            <div");

WriteLiteral(" class=\"col-md-7 col-xs-12 form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-update-diaChi\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Địa chỉ\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"                ");

WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"btn-footer\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success btn-save-infor-temp\"");

WriteLiteral(">Cập nhật thông tin</button>\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-light btn-cancel\"");

WriteLiteral(">Hủy bỏ</button>\r\n                        </div>\r\n                        ");

WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<style>\r\n    .modal-tach-thua {\r\n        width: 100" +
"%;\r\n        padding: 0px !important;\r\n        overflow: hidden !important;\r\n    " +
"    height: 100%;\r\n    }\r\n\r\n        .modal-tach-thua .modal-dialog {\r\n          " +
"  width: 100%;\r\n            padding: 5px;\r\n            margin: 0px;\r\n           " +
" height: 100%;\r\n        }\r\n\r\n        .modal-tach-thua .modal-header {\r\n         " +
"   position: relative;\r\n        }\r\n\r\n        .modal-tach-thua .modal-body {\r\n   " +
"         height: calc(100vh - 56px);\r\n            display: flex;\r\n            pa" +
"dding: 0px !important;\r\n        }\r\n\r\n    .map-tach-thua {\r\n        height: 100%;" +
"\r\n        width: calc(100% - 240px);\r\n        background-color: #f1f1f1;\r\n    }\r" +
"\n\r\n    .modal-tach-thua .menu-tach-thua {\r\n        width: 240px;\r\n        height" +
": 100%;\r\n        border-right: 1px solid #c3c3c3;\r\n        position: relative;\r\n" +
"    }\r\n\r\n    .map-tach-thua .modal-body {\r\n        position: relative;\r\n    }\r\n\r" +
"\n    .menu-tach-thua ul {\r\n        list-style-type: none;\r\n        margin: 0;\r\n " +
"       padding: 0;\r\n        width: 100%;\r\n        background-color: #f1f1f1;\r\n  " +
"  }\r\n\r\n    .menu-tach-thua li a {\r\n        display: block;\r\n        color: #000;" +
"\r\n        padding: 10px 16px;\r\n        text-decoration: none;\r\n    }\r\n\r\n        " +
".menu-tach-thua li a i {\r\n            font-size: 18px;\r\n        }\r\n        /* Ch" +
"ange the link color on hover */\r\n        .menu-tach-thua li a:hover {\r\n         " +
"   background-color: #48a0e2;\r\n            color: white;\r\n        }\r\n\r\n        ." +
"menu-tach-thua li a.active {\r\n            background-color: #48a0e2;\r\n          " +
"  color: white;\r\n        }\r\n\r\n    .table-point {\r\n        max-height: calc(100% " +
"- 400px);\r\n        background-color: white;\r\n    }\r\n\r\n    .button-tool {\r\n      " +
"  margin: 9px;\r\n        display: flex;\r\n        justify-content: space-between;\r" +
"\n    }\r\n\r\n        .button-tool .btn-default {\r\n            width: 45px;\r\n       " +
"     height: 40px;\r\n        }\r\n\r\n    .modal-tach-thua .modal-body .footer-map-po" +
"int {\r\n        position: absolute;\r\n        bottom: 0px;\r\n        z-index: 10;\r\n" +
"        background: white;\r\n        width: calc(100% - 240px);\r\n        padding:" +
" 0px;\r\n        height: 390px\r\n    }\r\n\r\n        .modal-tach-thua .modal-body .foo" +
"ter-map-point .header-point {\r\n            display: flex;\r\n            justify-c" +
"ontent: space-between;\r\n            height: 40px;\r\n            align-items: cent" +
"er;\r\n            padding: 0 25px;\r\n            background: #49aef9;\r\n           " +
" color: #fff;\r\n            font-size: 19px;\r\n        }\r\n\r\n    .footer-map-point " +
".context-point {\r\n        padding: 12px;\r\n    }\r\n\r\n        .footer-map-point .co" +
"ntext-point label {\r\n            font-size: 14px;\r\n            font-weight: 400;" +
"\r\n        }\r\n\r\n    .footer-map-point select {\r\n        border-radius: 0;\r\n      " +
"  -webkit-box-shadow: none !important;\r\n        box-shadow: none !important;\r\n  " +
"      color: #858585;\r\n        background-color: #FFF;\r\n        border: 1px soli" +
"d #D5D5D5;\r\n        padding: 3px 4px;\r\n        height: 30px;\r\n    }\r\n\r\n    .foot" +
"er-map-point input {\r\n        border-radius: 0 !important;\r\n        color: #8585" +
"85;\r\n        background-color: #FFF;\r\n        border: 1px solid #D5D5D5;\r\n      " +
"  padding: 5px 4px 6px;\r\n        font-size: 14px;\r\n        font-family: inherit;" +
"\r\n        -webkit-box-shadow: none !important;\r\n        box-shadow: none !import" +
"ant;\r\n        -webkit-transition-duration: .1s;\r\n        transition-duration: .1" +
"s;\r\n    }\r\n\r\n    .footer-map-point .form-actions {\r\n        display: flex;\r\n    " +
"    background-color: #F5F5F5;\r\n        margin-bottom: 20px;\r\n        margin-top" +
": 20px;\r\n        padding: 19px 20px 20px;\r\n        justify-content: center;\r\n   " +
"     padding: 0px !important;\r\n    }\r\n\r\n        .footer-map-point .form-actions " +
"button {\r\n            border-radius: 0px;\r\n            padding: 7px 18px;\r\n     " +
"       margin-left: 5px;\r\n        }\r\n\r\n    .footer-map-point .form-group input:d" +
"isabled, .footer-map-point .form-group input[disabled] {\r\n        color: #848484" +
" !important;\r\n        background-color: #EEE !important;\r\n    }\r\n\r\n    .footerHi" +
"de {\r\n        -webkit-animation-name: animationfooter; /* Safari 4.0 - 8.0 */\r\n " +
"       -webkit-animation-duration: 2s; /* Safari 4.0 - 8.0 */\r\n        animation" +
"-name: animationfooter;\r\n        animation-duration: 2s;\r\n        bottom: -350px" +
" !important;\r\n    }\r\n\r\n    .footerShow {\r\n        -webkit-animation-name: animat" +
"ionfooter1; /* Safari 4.0 - 8.0 */\r\n        -webkit-animation-duration: 2s; /* S" +
"afari 4.0 - 8.0 */\r\n        animation-name: animationfooter1;\r\n        animation" +
"-duration: 2s;\r\n        bottom: 0px;\r\n    }\r\n\r\n    ");

WriteLiteral("@keyframes animationfooter {\r\n        0% {\r\n            bottom: 0px;\r\n        }\r\n" +
"\r\n        100% {\r\n            bottom: -350px;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@-webkit-keyframes animationfooter {\r\n        0% {\r\n            bottom: 0px;\r\n   " +
"     }\r\n\r\n        100% {\r\n            bottom: -350px;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@keyframes animationfooter1 {\r\n        0% {\r\n            bottom: -350px;\r\n       " +
" }\r\n\r\n        100% {\r\n            bottom: 0px\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@-webkit-keyframes animationfooter1 {\r\n        0% {\r\n            bottom: -350px;\r" +
"\n        }\r\n\r\n        100% {\r\n            bottom: 0px\r\n        }\r\n    }\r\n\r\n    ." +
"infor-Tach-Thua {\r\n        width: 350px;\r\n        height: 100%;\r\n        positio" +
"n: absolute;\r\n        top: 0px;\r\n        /*right: 0px;*/\r\n        background: #f" +
"ff;\r\n        right: -350px\r\n    }\r\n\r\n        .infor-Tach-Thua .form-group {\r\n   " +
"         margin-bottom: 8px;\r\n            padding: 0px 9px;\r\n        }\r\n\r\n      " +
"  .infor-Tach-Thua .header-infor {\r\n            width: 100%;\r\n            height" +
": 30px;\r\n            background: #49aef9;\r\n            color: #fff;\r\n           " +
" display: flex;\r\n            justify-content: center;\r\n            align-items: " +
"center;\r\n            margin-bottom: 6px;\r\n        }\r\n\r\n            .infor-Tach-T" +
"hua .header-infor span {\r\n                position: absolute;\r\n                l" +
"eft: 7px;\r\n                cursor: pointer;\r\n                font-size: 17px;\r\n " +
"           }\r\n\r\n    .headerHide {\r\n        -webkit-animation-name: animationhead" +
"er; /* Safari 4.0 - 8.0 */\r\n        -webkit-animation-duration: 2s; /* Safari 4." +
"0 - 8.0 */\r\n        animation-name: animationheader;\r\n        animation-duration" +
": 2s;\r\n        right: -350px !important;\r\n    }\r\n\r\n    .headerShow {\r\n        -w" +
"ebkit-animation-name: animationheader1; /* Safari 4.0 - 8.0 */\r\n        -webkit-" +
"animation-duration: 2s; /* Safari 4.0 - 8.0 */\r\n        animation-name: animatio" +
"nheader1;\r\n        animation-duration: 2s;\r\n        right: 0px;\r\n    }\r\n\r\n    ");

WriteLiteral("@keyframes animationheader {\r\n        0% {\r\n            right: 0px;\r\n        }\r\n\r" +
"\n        100% {\r\n            right: -355px;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@-webkit-keyframes animationheader {\r\n        0% {\r\n            right: 0px;\r\n    " +
"    }\r\n\r\n        100% {\r\n            right: -355px;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral("@keyframes animationheader1 {\r\n        0% {\r\n            right: -355px;\r\n        " +
"}\r\n\r\n        100% {\r\n            right: 0px;\r\n        }\r\n    }\r\n\r\n    ");

WriteLiteral(@"@-webkit-keyframes animationheader1 {
        0% {
            right: -355px;
        }

        100% {
            right: 0px;
        }
    }

    .modal-tach-thua .btn-footer {
        /*position: absolute;*/
        bottom: 0px;
        width: 100%;
        display: flex;
    }

        .modal-tach-thua .btn-footer button {
            width: 50%;
            border-radius: 0px;
        }

    .modal-tach-thua .clearPoint {
        cursor: pointer;
        color: #ed4f4f;
    }

        .modal-tach-thua .clearPoint:hover {
            cursor: pointer;
            color: #f5a8a8;
        }

    .modal-tach-thua tr td {
        vertical-align: inherit !important;
    }

    .modal-tach-thua tr.active-select {
        background-color: #5da8e2;
        color: #fff;
    }

    .table-hover > tbody > tr:hover {
        background-color: #5da8e2 !important;
        color: #fff !important;
    }

    ");

WriteLiteral(@"@media (max-height: 810px) {

        .modal-tach-thua .footer-map-point .context-point {
            padding: 5px !important;
        }

        .modal-tach-thua .col-xs-12, .modal-tach-thua .col-sm-8,
        .modal-tach-thua .col-xs-6, .modal-tach-thua .col-sm-2,
        .modal-tach-thua .col-md-4, .modal-tach-thua .col-sm-12,
        .modal-tach-thua .col-sm-10, .modal-tach-thua .col-sm-4 {
            padding-right: 5px !important;
            padding-left: 5px !important;
        }

        .modal-body .footer-map-point {
            height: 320px !important;
        }

        .modal-tach-thua .footer-map-point .form-actions {
            margin-bottom: 5px;
            margin-top: 5px;
        }

        .modal-tach-thua .footer-map-point {
            padding: 0px !important;
        }

        .modal-tach-thua .footerHide {
            -webkit-animation-name: animationfooter; /* Safari 4.0 - 8.0 */
            -webkit-animation-duration: 2s; /* Safari 4.0 - 8.0 */
            animation-name: animationfooter;
            animation-duration: 2s;
            bottom: -280px !important;
        }
    }
</style>");

        }
    }
}
#pragma warning restore 1591
