#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_ToolRule.cshtml")]
    public partial class _Views_MapIOT__ToolRule_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__ToolRule_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"tool-rule\"");

WriteLiteral(">\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-common draw-width-height\"");

WriteLiteral(" title=\"Đo khoảng cách\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 125), Tuple.Create("\"", 164)
, Tuple.Create(Tuple.Create("", 131), Tuple.Create<System.Object, System.Int32>(Href("~/Images/MapIOT/Tool_Distance.png")
, 131), false)
);

WriteLiteral(" />\r\n    </button>\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-common draw-area\"");

WriteLiteral(" title=\"Đo diện tích\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 275), Tuple.Create("\"", 310)
, Tuple.Create(Tuple.Create("", 281), Tuple.Create<System.Object, System.Int32>(Href("~/Images/MapIOT/Tool_Area.png")
, 281), false)
);

WriteLiteral(" />\r\n    </button>\r\n    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn-common draw-replay\"");

WriteLiteral(" title=\"Xóa tất cả\"");

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 421), Tuple.Create("\"", 459)
, Tuple.Create(Tuple.Create("", 427), Tuple.Create<System.Object, System.Int32>(Href("~/Images/MapIOT/Tool_replay1.png")
, 427), false)
);

WriteLiteral(@" />
    </button>
</div>
<style>
    .tool-rule{
        position:absolute;
        top:6px;
        z-index: 10;
        left:347px;
    }
    .btn-common{
        
        padding: 6px 12px;
        background: #eff5f7;
        outline: none;
        border: 1px solid #2198f16b;
    }
    .btn-active{
        background:#99c1ce;
    }
</style>");

        }
    }
}
#pragma warning restore 1591
