#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/_UpdateThuaDat.cshtml")]
    public partial class _Views_MapIOT__UpdateThuaDat_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT__UpdateThuaDat_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"modal model-update-thua-dat\"");

WriteLiteral(" id=\"myModal\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" data-backdrop=\"static\"");

WriteLiteral(" data-keyboard=\"false\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n\r\n            <!-- Modal Header -->\r\n            <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"padding-bottom:0;\"");

WriteLiteral(">\r\n                <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Cập nhật thông tin thửa đất</h4>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"close-modal\"");

WriteLiteral(" class=\"close close-modal-iotlink\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">&times;</button>\r\n            </div>\r\n\r\n            <!-- Modal body -->\r\n       " +
"     <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Số hiệu tờ bản đồ</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soTo\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số hiệu tờ bản đồ\"");

WriteLiteral(" value=0");

WriteLiteral(" min=0");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Số thứ tự thửa</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-update-soThua\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số thứ tự thửa\"");

WriteLiteral(" value=0");

WriteLiteral(" min=0");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Tờ bản đồ cũ</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-soTo-old\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Thửa cũ</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-soThua-old\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Diện tích</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-dienTich\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Diện tích pháp lý</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-dienTichPhapLy\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Mục đích sử dụng</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" class=\"MucDichSuDung form-style\"");

WriteLiteral("></label>\r\n                            </div>\r\n                        </div>\r\n  " +
"                  </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Tên chủ</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-chuNha\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" class=\"control-label col-md-4 col-xs-12 required\"");

WriteLiteral(">Địa chỉ</label>\r\n                    <div");

WriteLiteral(" class=\"col-md-8 col-xs-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n                                <label");

WriteLiteral(" id=\"text-update-diaChi\"");

WriteLiteral(" class=\"form-style\"");

WriteLiteral(" />\r\n                            </div>\r\n                        </div>\r\n        " +
"            </div>\r\n                </div>\r\n            </div>\r\n\r\n            <!" +
"-- Modal footer -->\r\n            <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Thoát</button>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btn-update-thua-dat\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Lưu lại</button>\r\n            </div>\r\n\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<s" +
"tyle>\r\n    .model-update-thua-dat .row.form-group {\r\n        height: 45px;\r\n    " +
"    display: flex;\r\n        align-items: center;\r\n    }\r\n</style>");

        }
    }
}
#pragma warning restore 1591
