#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using FIOLIS.Modules.Map;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/MapIOT/Index.cshtml")]
    public partial class _Views_MapIOT_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_MapIOT_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\MapIOT\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutMapIOT.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"mapObject defective\"");

WriteLiteral(" id=\"map\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"input-box text-center clearable-input\"");

WriteLiteral(">\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"button-search tooltip-setting\"");

WriteLiteral(" id=\"tooltip-searchsetting\"");

WriteLiteral("></button><span");

WriteLiteral(" class=\"tooltiptextsetting\"");

WriteLiteral(">Tìm kiếm nâng cao</span>\r\n        <input");

WriteLiteral(" class=\"search-text\"");

WriteLiteral(" id=\"id-search-text\"");

WriteLiteral(" placeholder=\"Số tờ, Số thửa\"");

WriteLiteral(" maxlength=\"11\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" oninput=\"this.value = this.value.replace(/[^0-9,]/g, \'\').replace(/(\\..*)\\./g, \'$" +
"1\');\"");

WriteLiteral(">\r\n        <span data-clear-input");

WriteLiteral(" id=\"clear-input-id\"");

WriteLiteral(" class=\"glyphicon glyphicon-remove-circle\"");

WriteLiteral("></span>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"button-search tooltip-search\"");

WriteLiteral(" id=\"tooltip-search\"");

WriteLiteral("></button><span");

WriteLiteral(" class=\"tooltiptext\"");

WriteLiteral(">Tìm kiếm</span>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(" id=\"advSearch\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"note\"");

WriteLiteral(">\r\n                <p>Tìm kiếm nâng cao</p>\r\n            </div>\r\n\r\n            <d" +
"iv");

WriteLiteral(" class=\"form-content form-search\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-search-soTo\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số hiệu tờ BĐ\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" id=\"text-search-soThua\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Số thứ tự thửa\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-search-MDSuDung\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Ký hiệu MĐSD\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"col-md-6\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-search-chuNha\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Tên chủ sở hữu\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" id=\"lstSelectSearch-adv\"");

WriteLiteral("></select>\r\n                        </div>\r\n                    </div>\r\n         " +
"           <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"text-search-diaChi\"");

WriteLiteral(" class=\"form-control form-style\"");

WriteLiteral(" placeholder=\"Địa chỉ\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n                " +
"</div>\r\n                <center><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btnSubmit\"");

WriteLiteral(" id=\"tooltip-search-adv\"");

WriteLiteral(">Tìm kiếm</button></center>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"list-search-adv\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"location-click\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"image-click\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" class=\"content-location\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"address-menu-click\"");

WriteLiteral(" style=\"font-weight: bold;\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"location-menu-click\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" class=\"location-menu-click-vn2000\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"close-content\"");

WriteLiteral(">\r\n            <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    ");

            
            #line 69 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_ChuGiai"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 70 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_ToolRule"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" id=\"loading-map\"");

WriteLiteral(" class=\"loading-map\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3660), Tuple.Create("\"", 3693)
, Tuple.Create(Tuple.Create("", 3666), Tuple.Create<System.Object, System.Int32>(Href("~/Images/MapIOT/loading.gif")
, 3666), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(" class=\"download-file\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" href=\"\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" download>Newsletter</a>\r\n</div>\r\n");

            
            #line 78 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_DetailProperty"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Stylesheet", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3894), Tuple.Create("\"", 3924)
, Tuple.Create(Tuple.Create("", 3901), Tuple.Create<System.Object, System.Int32>(Href("~/Content/jquery-ui.css")
, 3901), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 3956), Tuple.Create("\"", 3989)
, Tuple.Create(Tuple.Create("", 3963), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/Extra.css")
, 3963), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4021), Tuple.Create("\"", 4056)
, Tuple.Create(Tuple.Create("", 4028), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/select2.css")
, 4028), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4088), Tuple.Create("\"", 4122)
, Tuple.Create(Tuple.Create("", 4095), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/Common.css")
, 4095), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4154), Tuple.Create("\"", 4179)
, Tuple.Create(Tuple.Create("", 4161), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 4161), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4211), Tuple.Create("\"", 4245)
, Tuple.Create(Tuple.Create("", 4218), Tuple.Create<System.Object, System.Int32>(Href("~/Content/fileinput.min.css")
, 4218), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4275), Tuple.Create("\"", 4325)
, Tuple.Create(Tuple.Create("", 4282), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/DetailObjectProperties.css")
, 4282), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4357), Tuple.Create("\"", 4392)
, Tuple.Create(Tuple.Create("", 4364), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/ChuGiai.css")
, 4364), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4424), Tuple.Create("\"", 4462)
, Tuple.Create(Tuple.Create("", 4431), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/mapcontrol.css")
, 4431), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4494), Tuple.Create("\"", 4530)
, Tuple.Create(Tuple.Create("", 4501), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/MenuLeft.css")
, 4501), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4562), Tuple.Create("\"", 4600)
, Tuple.Create(Tuple.Create("", 4569), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/ImportFile.css")
, 4569), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 4632), Tuple.Create("\"", 4664)
, Tuple.Create(Tuple.Create("", 4639), Tuple.Create<System.Object, System.Int32>(Href("~/Content/MapIOT/Home.css")
, 4639), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4720), Tuple.Create("\"", 4753)
, Tuple.Create(Tuple.Create("", 4726), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/select2.js")
, 4726), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4777), Tuple.Create("\"", 4814)
, Tuple.Create(Tuple.Create("", 4783), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/bootbox.min.js")
, 4783), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4838), Tuple.Create("\"", 4876)
, Tuple.Create(Tuple.Create("", 4844), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/jsCheckInput.js")
, 4844), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4900), Tuple.Create("\"", 4934)
, Tuple.Create(Tuple.Create("", 4906), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/turf.min.js")
, 4906), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4958), Tuple.Create("\"", 5013)
, Tuple.Create(Tuple.Create("", 4964), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/FtilisScripts/WebGIS/Geodesy/Problem.js")
, 4964), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5037), Tuple.Create("\"", 5077)
, Tuple.Create(Tuple.Create("", 5043), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/sweetalert.min.js")
, 5043), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5101), Tuple.Create("\"", 5139)
, Tuple.Create(Tuple.Create("", 5107), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/toolTachThua.js")
, 5107), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5239), Tuple.Create("\"", 5285)
, Tuple.Create(Tuple.Create("", 5245), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/fiolissdk@1.3.9.prod.js")
, 5245), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5309), Tuple.Create("\"", 5356)
, Tuple.Create(Tuple.Create("", 5315), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/jquery.nicescroll.min.js")
, 5315), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5380), Tuple.Create("\"", 5426)
, Tuple.Create(Tuple.Create("", 5386), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/plugins/inputmask/inputmask.js")
, 5386), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5450), Tuple.Create("\"", 5503)
, Tuple.Create(Tuple.Create("", 5456), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/plugins/inputmask/jquery.inputmask.js")
, 5456), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5527), Tuple.Create("\"", 5562)
, Tuple.Create(Tuple.Create("", 5533), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/ToolShape.js")
, 5533), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5586), Tuple.Create("\"", 5619)
, Tuple.Create(Tuple.Create("", 5592), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/ThuaDat.js")
, 5592), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5771), Tuple.Create("\"", 5810)
, Tuple.Create(Tuple.Create("", 5777), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/UpdateThuaDat.js")
, 5777), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5834), Tuple.Create("\"", 5868)
, Tuple.Create(Tuple.Create("", 5840), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/MenuLeft.js")
, 5840), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5892), Tuple.Create("\"", 5928)
, Tuple.Create(Tuple.Create("", 5898), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/ImportFile.js")
, 5898), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 5952), Tuple.Create("\"", 5984)
, Tuple.Create(Tuple.Create("", 5958), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/Mode3D.js")
, 5958), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6072), Tuple.Create("\"", 6108)
, Tuple.Create(Tuple.Create("", 6078), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/MapControl.js")
, 6078), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6132), Tuple.Create("\"", 6166)
, Tuple.Create(Tuple.Create("", 6138), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/TachThua.js")
, 6138), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6190), Tuple.Create("\"", 6223)
, Tuple.Create(Tuple.Create("", 6196), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/HopThua.js")
, 6196), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6247), Tuple.Create("\"", 6282)
, Tuple.Create(Tuple.Create("", 6253), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/EditShape.js")
, 6253), false)
);

WriteLiteral("></script>\r\n    ");

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6508), Tuple.Create("\"", 6541)
, Tuple.Create(Tuple.Create("", 6514), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/ChuGiai.js")
, 6514), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6565), Tuple.Create("\"", 6600)
, Tuple.Create(Tuple.Create("", 6571), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/ConfigUrl.js")
, 6571), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6624), Tuple.Create("\"", 6664)
, Tuple.Create(Tuple.Create("", 6630), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/buttonTachThua.js")
, 6630), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6688), Tuple.Create("\"", 6728)
, Tuple.Create(Tuple.Create("", 6694), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/SyncServiceFTI.js")
, 6694), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 6752), Tuple.Create("\"", 6782)
, Tuple.Create(Tuple.Create("", 6758), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/MapIOT/InAn.js")
, 6758), false)
);

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" src=\"https://js.arcgis.com/4.14/\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var currentMaXa;\r\n        $(function () {\r\n            //d3 = window.d" +
"3;\r\n            lstHuyenNguoiDung = ");

            
            #line 134 "..\..\Views\MapIOT\Index.cshtml"
                           Write(Html.Raw(Json.Encode(ViewBag.HuyenNguoiDung)));

            
            #line default
            #line hidden
WriteLiteral(";\r\n            currentMaXa = \"");

            
            #line 135 "..\..\Views\MapIOT\Index.cshtml"
                      Write(Html.Raw(ViewBag.BanDoXaID));

            
            #line default
            #line hidden
WriteLiteral(@""";
            ViewMap.CONSTS.codeDefault = currentMaXa.length > 0 ? currentMaXa : ViewMap.CONSTS.codeDefault;
            ViewMap.init();
            ToolShape.init();
            UpdateThuaDat.init();
            TachThua.init();
            HopThua.init();
            EditShape.init();
            MenuLeft.init();
            ImportFile.init();
            EditMode3D.init();
            MapControl.init();
            //MapControl.initMode3D();
            $("".object-mode-3d1"").select2();
            InAn.init();
        })
        function GetAllShapOnWardLatLng() {
            ViewMap.showThuaDatSelectSubdistrict();
        }
    </script>
");

WriteLiteral("    ");

            
            #line 155 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_TachThua"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 156 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_InforHopThua"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 157 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_UpdateThuaDat"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 158 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_TrichXuatFile"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 159 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_BienTap"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 160 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_NhapDuLieuFile"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 161 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_EditMode3D"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 162 "..\..\Views\MapIOT\Index.cshtml"
Write(Html.Partial("_EditThuaDat"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
